# Performance optimizations
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC -Dfile.encoding=UTF-8

# Kotlin & KAPT incremental compilation
kotlin.incremental=true
kotlin.caching.enabled=true
kapt.incremental.apt=true
kapt.include.compile.classpath=false
